//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PrimeiroExemploEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class FUNCIONARIO
    {
        public int ID { get; set; }
        public string NOME { get; set; }
        public Nullable<System.DateTime> DATA_NASCIMENTO { get; set; }
        public string RG { get; set; }
        public string CPF { get; set; }
        public int ID_USUARIO { get; set; }
        public int ID_STATUS { get; set; }
    
        public virtual TBL_USUARIO TBL_USUARIO { get; set; }
        public virtual STATUS STATUS { get; set; }
    }
}
