SET IDENTITY_INSERT [dbo].[Estado] ON
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (1, N'AC', N'Acre')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (2, N'AL', N'Alagoas')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (3, N'AM', N'Amazonas')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (4, N'AP', N'Amapá')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (5, N'BA', N'Bahia')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (6, N'CE', N'Ceará')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (7, N'DF', N'Distrito Federal')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (8, N'ES', N'Espírito Santo')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (9, N'GO', N'Goiás')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (10, N'MA', N'Maranhão')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (11, N'MG', N'Minas Gerais')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (12, N'MS', N'Mato Grosso do Sul')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (13, N'MT', N'Mato Grosso')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (14, N'PA', N'Pará')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (15, N'PB', N'Paraíba')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (16, N'PE', N'Pernambuco')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (17, N'PI', N'Piauí')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (18, N'PR', N'Paraná')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (19, N'RJ', N'Rio de Janeiro')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (20, N'RN', N'Rio Grande do Norte')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (21, N'RO', N'Rondônia')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (22, N'RR', N'Roraima')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (23, N'RS', N'Rio Grande do Sul')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (24, N'SC', N'Santa Catarina')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (25, N'SE', N'Sergipe')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (26, N'SP', N'São Paulo')
INSERT [dbo].[Estado] ([IdEstado], [Sigla], [Descricao]) VALUES (27, N'TO', N'Tocantins')
SET IDENTITY_INSERT [dbo].[Estado] OFF